development:
  adapter: mysql2
  database: sample_app
  encoding: utf8
  username: root
  password: '12345678'
  host: 127.0.0.1
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  encoding: utf8
  database: sample_app
  username: root
  password: "12345678"
  host: 127.0.0.1
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: sample_app
  encoding: utf8
  username: root
  password: '12345678'
  host: 127.0.0.1
  pool: 5
  timeout: 5000